-- Finding total customers by country:
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country 
ORDER BY total_customers DESC

-- Find total customers by gender:
SELECT 
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender 
ORDER BY total_customers DESC

-- Find total products by category:
SELECT 
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category 
ORDER BY total_products DESC

-- Avg cost in each category:
SELECT 
category,
AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category 
ORDER BY avg_cost DESC

-- Total Revenue generated by each category:
SELECT

p.category,
SUM(f.sales_amount) AS total_revenue

FROM gold.facts_sales f

LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key

GROUP BY p.category
ORDER BY total_revenue DESC

-- Total Revenue Generated by each customer:
SELECT 

c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue

FROM gold.facts_sales f

LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key

GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

-- Distribution of sold items by countries:
SELECT 

c.country,
SUM(f.quantity) AS total_sold_items

FROM gold.facts_sales f

LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key

GROUP BY 
c.country
ORDER BY total_sold_items DESC